apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  annotations:
     service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    k8s-app: grafana
